server:
  port: 8080
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "authentication"
    schema: "public"
    username: "auth"
    password: "auth"
logging:
  level:
    root: INFO
    co.com.crediya.authentication: DEBUG
jwt:
  secret: "DQpKdWFuIFNhbmNoZXogQm9vdGNhbXAgUG93ZXIgVXAgMjAyNQ"
  expiration: 3600000