adapters:
  r2dbc:
    host: ${DB_HOST}
    port: 5432
    database: ${DB_NAME}
    schema: public
    username: ${DB_USER}
    password: ${DB_PASS}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}