server:
  port: 8080
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: 5432
    database: "${DB_NAME}"
    schema: "public"
    username: "${DB_USER}"
    password: "${DB_PASS}"
logging:
  level:
    root: INFO
    co.com.crediya.authentication: DEBUG
jwt:
  secret: "${JWT_SECRET}"
  expiration: ${JWT_EXPIRATION}